add info panel
epoch-dev/epoch-forgotten-client pull request #126
Opened 2024-10-23 16:17 UTC by domgan

* info panel with tutorial on basic controls and roadmap
* basic css, we can expand on background style etc
* improved aside section
* created `buttons.scss`
![image](https://github.com/user-attachments/assets/812dc970-38c0-40c8-bf30-1235ecb2a661)

2024-10-24 17:48 UTC, matfij commented on src/common/styles/buttons.scss
> +}
we have some other common button classes in `utils.scss` should probably be moved here, also other button-related classes were abbreviated `btn` so we should either update them to `button` or rename this new one to `btn`.

2024-10-24 17:51 UTC, matfij commented on src/views/game/GameComponent.tsx
> +    const AsidePanel = () => (
why mixing rendering with other if no arguments are required?

2024-10-24 17:52 UTC, matfij requested changes
Instead of a roadmap (which should be included in some external resource (like public notion page/wiki or github pages) we should add instructions for battles.

2024-10-24 17:53 UTC, domgan commented on src/views/game/GameComponent.tsx
> +    const AsidePanel = () => (
Dunno what you mean

2024-10-24 17:54 UTC, domgan commented
* I think roadmap is a nice thing for players to see so they know what to expect and what was done
* Agreed with battle instructions. I myself don't know how it works so feel free to expand yourself

2024-10-24 18:07 UTC, domgan commented
* I like having a guide post as a general place of comms with players, at least for now. We can expand on that idea.
* I think we should explain basics of resistances, physical attacks and defenses.

2024-10-24 18:09 UTC, matfij commented on src/views/game/GameComponent.tsx
> +    const AsidePanel = () => (
Why create a function for rendering it when no arguments are required to render and it makes component more convoluted by placing TSX where usually TS is placed.

2024-10-24 18:13 UTC, domgan commented on src/views/game/GameComponent.tsx
> +    const AsidePanel = () => (
> Why create a function for rendering it when no arguments are required to render

And why create functions? Code organization and readability.

> it makes component more convoluted by placing TSX where usually TS is placed

Why "usually"? That's not aligned with my experience.

2024-10-25 18:48 UTC, matfij approved these changes
LGTM

2024-10-25 18:51 UTC, merged